version: '3.4'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ${HOME}/ifeds/datasetfile:/app/datasetFile
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/ifeds}
      - SPRING_DATASOURCE_USERNAME=ifeds
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_INITIALIZATION-MODE=always
      - SPRING_JPA_HIBERNATE_DDL-AUTO=none
    restart: always
networks:
  default:
    external:
      name: ${IFEDS_NETWORK:-ifeds-network}
